const { database } = require("./database.js")
const {totalTrailMiles, shortestTrail, longTrail, totalRiverMiles, shortestRiver, longRiver,
    mostExpensive, leastExpensive, mostExpensiveRiver, leastExpensiveRiver} = require("./function.js")
const {art} = require("./displayHead.js")
const {getTrailLogs} = require("./trails.js")
const {showRivers} = require("./rivers.js")

console.log(art)
const trailTotal = totalTrailMiles(database.trails)
const shortTrail = shortestTrail(database.trails)
const longest = longTrail(database.trails)
const riverTotal = totalRiverMiles(database.rivers)
const shortRiver = shortestRiver(database.rivers)
const longestRiver = longRiver(database.rivers)
let expense = mostExpensive(database.trails)
let inexpense = leastExpensive(database.trails)
let expenseRiver = mostExpensiveRiver(database.rivers)
let inexpenseRiver = leastExpensiveRiver(database.rivers)
console.log(shortTrail)
getTrailLogs(trailTotal, shortTrail, longest, expense, inexpense, database.trails)
showRivers(riverTotal, shortRiver, longestRiver, expenseRiver, inexpenseRiver, database.rivers)